- README.md
- fragments/imageFragments.js
@KyleAMathews was kind enough to point out that there is no reason not to include the WebP versions  - they are optional in other plugins because they add to the build time, but since we let the Sanity CDN scale and transform our images, we can include them without any penalty. 
I've retained the fragments in code so as not to break people's build, but removed them from the readme - we should probably remove them in the next major release.
> Include WebP in all image fragments

- README.md
- src/gatsby-node.ts
- src/util/normalize.ts
This PR adds a `materializeReferences` argument to raw fields, which will recursively replace any objects containing `_ref` with the referenced node, if it can be found. 
Since the return value is untyped, there is unfortunately no way to use image fragments and such, but this is still useful in a bunch of other contexts.
The argument is `false` by default in order to maintain backwards compatibility.
> Add ability to materialize references within raw fields

- src/gatsby-node.ts
- src/types/gatsby.ts
- src/types/sanity.ts
- src/util/getGraphQLResolverMap.ts
- src/util/normalize.ts
- src/util/remoteGraphQLSchema.ts
- src/util/rewriteGraphQLSchema.ts
Fixes #15
When a field is a union type, it currently seems to always resolve to null.
This PR adds resolvers to all fields which is of a union type, and explicitly resolves them using `getNodeById`.
> Explicitly declare field resolvers for union fields

- README.md
- src/util/remoteGraphQLSchema.ts
We are now using the schemas in such an extent that it doesn't make sense anymore to try to allow inference to still work. I suggest we bump to 3.0.0 and make it mandatory for the plugin to work.
> Make deployed GraphQL API a requirement

- CHANGELOG.md
- README.md
- src/gatsby-node.ts
- src/util/documentIds.ts
- src/util/handleDrafts.ts
- src/util/handleListenerEvent.ts
- src/util/normalize.ts
- src/util/resolveReferences.ts
- test/resolveReferences.test.ts
This PR checks if a document ID matches the asset ID pattern we use in Sanity, and if so, preserves it. This ensures that using it with the image-url library and similar is easier, as you don't need to materialize references to get at the asset document ID.
I also:
- Removed the old Gatsby references resolving, as it was no longer used. Hooray for removing dead code!
- Rewired `_rawSomeFieldName` in resolved, referenced nodes to their original field name (eg `_rawSections` =>  `sections`)
- Broken references now return `null` instead of the reference object, making it easier to see when resolving fails
> Preserve asset IDs, rewire raw fields on resolved references

- src/gatsby-node.ts
- src/util/getGraphQLResolverMap.ts
- src/util/normalize.ts
- src/util/rewriteGraphQLSchema.ts
Fixes #39.
Gatsby has some properties which are considered "internal", or rather, they have a special meaning and should not be used. These are the following: id, parent, children, fields, internal.
When these occur in the schema (and data), we rename the fields to include a `sanity` prefix - in other words, `internal` becomes `sanityInternal`.
However, when you had a field which needed the prefix which _also_ needed a custom resolver (such as an array or a reference), the resolver would get applied to the unprefixed field, causing Gatsby to crash on build, as we were trying to change the output type of the field.
I also took the liberty of adding warnings when we rename conflicting fields, as this can be quite confusing to users.
> Apply resolvers to conflict-free restricted fields

- README.md
- src/gatsby-node.ts
- src/util/remoteGraphQLSchema.ts
This adds support for specifying the GraphQL API tag name to use for introspecting the schema.
> Allow specifying GraphQL API tag

- src/util/getGraphQLResolverMap.ts
- src/util/rewriteGraphQLSchema.ts
If you have a non-document type with fields that are reserved (`id`, for instance), the field would still get renamed, even though it doesn't implement the `Node` interface. To make things worse, the renaming of _data_ is not done recursively, so you would be unable to query these fields.
This also fixes the issue where users were seeing a warning about the `SanityImageAssetSource` having a `id` attribute upon build. 
This is actually a breaking change, as some people might be relying on the `sanity`-prefixed field names, so I guess this calls for a major release.
Fixes #63
> Fix bug where non-document types would get rewritten fields

- src/gatsby-node.ts
- src/types/gatsby.ts
- src/util/documentIds.ts
- src/util/getGraphQLResolverMap.ts
- src/util/remoteGraphQLSchema.ts
- src/util/resolveReferences.ts
- src/util/rewriteGraphQLSchema.ts
- test/resolveReferences.test.ts
Roughly speaking, if you have a complex field (such as a portable text field) that is not at the root level of a document, there is no way to only fetch that field in it's "raw" variant.
For instance, with the following schema:
```graphql
type TravelLog implements Document {
title: String
body: [Block]
locations: [TravelLocation]
}
type TravelLocation {
name: String
description: [Block]
highlights: [TravelLocationHighlight]
geolocation: Geopoint
}
type TravelLocationHighlight {
title: String
description: [Block]
}
```
If you want to fetch travel log entries with their title and highlights only, there is no way to do that except to use the `_rawLocations` field on the `TravelLog` type, which would also give the `description` and `geolocation` field from the `TravelLocation` type, which we …
> Re-implement aliases, allowing deep, raw aliases

- src/images/extendImageNode.ts
- src/images/getGatsbyImageProps.ts
- test/__snapshots__/getGatsbyImageProps.test.ts.snap
This PR aligns the image fragments we provide with that of gatsby-image:
- Certain properties (`src`, `srcSet` etc) should be set as non-nulls (fixes typescript inference)
- `aspectRatio` should not be returned on fixed images
- `base64` should be `undefined` if not available, not `null`
Fixes #57
> Align image fragments with gatsby-image

- README.md
This matches the rest of the examples. Small item, but can be a frustrating tripping point for copy-pasters and beginners alike :)
> make env variable consistent across examples

- package.json
Supports type resolution when importing into a TypeScript project. Addresses issue #78.
> Adding types property to package.json

- src/gatsby-node.ts
Currently we set up a listener for all documents in the dataset and exclude system documents after mutation event is received. With this patch we instead exclude system documents in the query itself, which saves a bit of bandwidth for listeners events we don't care about.
> Exclude system documents in listener query

- src/images/getGatsbyImageProps.ts
- src/index.ts
The `getFixedGatsbyImage` and `getFluidGatsbyImage` `toFormat` argument expects a value from the enum `ImageFormat` this is not exported anywhere thus when using this in TS you will get type error.
> Export `ImageFormat` type.

- README.md
Added the way to retrieve all required config values via a simple command that mentioned in the [docs](https://www.sanity.io/docs/http-auth). I think it will save some time for the ones like me who had a hard time finding it.
> docs: extra info added to retrieve tokens easier

- package.json
Hello, Gatsby maintainer here 👋 
While looking at the plugin I noticed that the `peerDependency` on `gatsby` is set incorrectly. We're in the process of providing more helpful information on the `/plugins` page of our website and for that we need plugins to set their `peerDependencies` correctly/more specific.
At the moment you say that _any_ version (v4, v5, v6, etc.) will work with this even when in between we'd introduce breaking changes.
Making it more explicit is the safer choice (in the future you'll be able to mark breaking changes with explicit version ranges) and will allow us to display the plugin as compatible to versions X, Y, Z.
I've also updated the Node engines field as v3 requires at least 12.13.0
Thanks!
> fix: Set more specific peer deps + engines update

- README.md
- src/gatsby-node.ts
- src/images/extendImageNode.ts
- src/images/getGatsbyImageProps.ts
This partially reverts commit d7ca4624034e43599b51d1bb5008c56707ed4f47, bringing back the gatsbyImageData node and updates readme with improved code examples
> chore: restore gatsbyImageData on image nodes

- src/util/getAllDocuments.ts
Since v7 the `overlayDrafts` option is not working anymore.
The issue seems to be a wrong check in `getAllDocuments` that removes the drafts when they should be included
> fix drafts handle in getAllDocuments

- src/images/getGatsbyImageProps.ts
- test/__snapshots__/getGatsbyImageProps.test.ts.snap
This PR changes the source metadata to be hardcoded to `auto` to fix safari 13 issues with webp and gatsby v3
> fix: use correct format in sourceMetadata

- README.md
- package.json
- src/gatsby-node.ts
Customization for large projects that change often to the point of breaking watch mode. With `watchModeBuffer` these users can specify higher values to batch node updates and prevent breaks.
Closes #135
> feat: configurable watch buffer timer

- README.md
- package.json
- src/gatsby-node.ts
Tries to fix Gatsby panicking when we update too many nodes non-stop (see error message below). Instead of relying on a fixed `bufferTime` to batch updates, we're now waiting until Gatsby's internals are quiet to run updates.
```
Panicking because nodes appear to be being changed every time we run queries.
This would cause the site to recompile infinitely.
Check custom resolvers to see if they are unconditionally creating or mutating
nodes on every query.
This may happen if they create nodes with a field that is different every time,
such as a timestamp or unique id.
```
> refactor(watchMode): wait on Gatsby's internals before node updates

- CHANGELOG.md
- package.json
- src/util/resolveReferences.ts
This PR resolves issues which occurs for Incremental Builds in Gatsby, when using the plugin.
The way that the Incremental Builds feature works is that it marks routes (HTML files + JSON page data) for regeneration if any of the following inputs change: https://www.gatsbyjs.com/docs/debugging-incremental-builds/#how-does-it-work
Our team experienced an issue where files were getting marked for regeneration on every build, even with no frontend code changing, or updates in the CMS.
The result of diffing between builds showed that the `page-data/*.json` files being outputted by the gatsby build had a changing value for the `counter` property in the `internal` object, sourced by the `gatsby-source-sanity` plugin: 
This is a bug, since the counter result is changed between builds and these …
> fix: don't add gatsby internals to resolved reference gatsby nodes

- src/gatsby-node.ts
Helps incremental builds of large datasets by paginating fetching of document IDs, and optimizing their lookups using a set. Fixes #149.
> fix: helps incremental builds of large datasets by paginating

- README.md
Companion PR for https://github.com/gatsbyjs/gatsby/pull/36566
Updates your README to account for `gatsby-plugin-image` + made some other small tweaks.
Should  superseed these (and then they can be closed):
- https://github.com/sanity-io/gatsby-source-sanity/pull/158
- https://github.com/sanity-io/gatsby-source-sanity/pull/111
> Update README for `gatsby-plugin-image` and other

- package-lock.json
- package.json
One of the changes that were merged between `gatsby-source-sanity` 7.5.1 and 7.6.0 is a major version bump for axios (v0 to v1) in https://github.com/sanity-io/gatsby-source-sanity/pull/185.
Was able to reproduce the behavior shown in https://github.com/sanity-io/gatsby-source-sanity/issues/200 via https://github.com/taulal/gatsby-source-sanity-bug-repo and fix it by [adding a resolution that pins axios to v0 again](https://github.com/tyhopp/gatsby-source-sanity-bug-repo/commit/4dbe7b718d931bca7865e7617858f5b73df4da03#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519).
Briefly looked for some direction from axios about what would need to change in [`getDocumentStream`](https://github.com/sanity-io/gatsby-source-sanity/blob/main/src/util/getDocumentStream.ts) to make it …
> fix(deps): Revert axios v1 bump in #185

- src/gatsby-node.ts
In order to perform a correct pagination base on `_id > $prevId`, all the ids should be ordered.
With this patch the order is enforced
> fix: getDocumentIds pagination query if custom _id values are used

- .gitignore
- src/util/getGraphQLResolverMap.ts
- src/util/normalize.ts
- src/util/rewriteGraphQLSchema.ts
We would like to add Sanity support to Netlify Connect, but the requirements for schemas are stricter than for Gatsby. This PR changes the schema to use `@link` directives instead of custom resolvers. As well as supporting Netlify Connect, having a stricter schema allows Gatsby to use performance optimisations that aren't possible with custom resolvers. As well as switching reference resolvers to `@link`, this changes union resolvers to instead add `internal.type` values to union fields. Doing this means we can remove all of the custom resolvers, apart from those used for raw fields.
> feat: use `@link` directive instead of custom resolvers

- README.md
- src/gatsby-node.ts
- src/util/cache.ts
- src/util/getSyncWithGatsby.ts
- src/util/normalize.ts
- src/util/remoteGraphQLSchema.ts
- src/util/rewriteGraphQLSchema.ts
- src/util/validateConfig.ts
This PR adds support for setting a custom type prefix, which allows multiple instances of the plugin to be used. The prefix is in addition to the `Sanity` prefix, so for example if you have a `movies` type, setting the type prefix to `Staging` will make the type `StagingSanityMovies`.
> feat: add support for type prefix

- src/util/getGraphQLResolverMap.ts
PR #242 tried to improve efficiency of resolution by using Gatbsy's built-in `@link` directives rather than custom resolvers for all references. However it caused a regression (#245) in cases where there is a list type with a union that contains a mix of references and inline nodes. This isn't a pattern that can be represented in Gatsby by default, so the `@link` directive failed. Alongside this, lists of references don't have the `@reference` directive added in the Sanity schema, so there is no way to determine if they are inline or references. This meant we can't reliably add `@link` directives for these.
For thios reason, this PR adds back custom resolvers for lists.
I have tested this locally with many sorts of lists and it works well, but I would like to work out a way to add better …
> fix: use resolver for lists

- packages/gatsby-source-sanity/src/util/normalize.ts
Simple check that we do not add a configured prefix more than once, as was happening in certain situations
> fix: only apply prefix once

- packages/gatsby-source-sanity/src/util/handleDeltaChanges.ts
The `lastBuildTime` variable was incorrectly typed as a `Date`, while it is actually a `string` returned by the cache system.
This caused a silent runtime error: `toISOString is not a function`
which resulted in the delta check always failing and all documents being re-synced.
This commit corrects the type and ensures proper handling of `lastBuildTime`.
1. Run `gatsby develop` twice.
2. On the second run, verify that only changed documents are synced with Sanity.
> fix handleDeltaChanges with correct lastBuildTime type
